# Generated by Django 2.2.10 on 2020-03-10 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('date_creation', models.DateField(auto_now=True)),
                ('date_start', models.DateField(auto_now=True)),
                ('date_finish', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.ManyToManyField(related_name='_profile_friends_+', to='holpoint.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoteIdeaInGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holpoint.Group')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holpoint.Idea')),
                ('votes', models.ManyToManyField(related_name='voted_ideas', to='holpoint.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='idea',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='holpoint.Profile'),
        ),
        migrations.AddField(
            model_name='idea',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_ideas', to='holpoint.Profile'),
        ),
        migrations.AddField(
            model_name='group',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to='holpoint.Profile'),
        ),
        migrations.AddField(
            model_name='group',
            name='ideas',
            field=models.ManyToManyField(blank=True, related_name='groups', through='holpoint.VoteIdeaInGroup', to='holpoint.Idea'),
        ),
        migrations.AddField(
            model_name='group',
            name='prefered_idea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='holpoint.Idea'),
        ),
        migrations.AddField(
            model_name='group',
            name='profiles',
            field=models.ManyToManyField(related_name='groups', to='holpoint.Profile'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_comments', to='holpoint.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_activities', to='holpoint.Profile')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='holpoint.Group')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_activities', to='holpoint.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='IdeaComment',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='holpoint.Comment')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='holpoint.Idea')),
            ],
            bases=('holpoint.comment',),
        ),
        migrations.CreateModel(
            name='ActivityComment',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='holpoint.Comment')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='holpoint.Activity')),
            ],
            bases=('holpoint.comment',),
        ),
    ]
