# Generated by Django 2.2.10 on 2020-02-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holpoint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
