# Generated by Django 2.2.10 on 2020-02-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holpoint', '0002_auto_20200221_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(related_name='_profile_friends_+', to='holpoint.Profile'),
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
