# Generated by Django 2.2.10 on 2020-03-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holpoint', '0003_auto_20200310_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteideaingroup',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='voted_ideas', to='holpoint.Profile'),
        ),
    ]
