# Generated by Django 2.2.10 on 2020-02-21 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holpoint', '0003_auto_20200221_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_creator', to='holpoint.Profile'),
        ),
        migrations.AddField(
            model_name='activity',
            name='likes',
            field=models.ManyToManyField(related_name='activity_likes', to='holpoint.Profile'),
        ),
    ]
