# Generated by Django 2.2.10 on 2020-03-02 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holpoint', '0003_auto_20200229_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='group',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='idea',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='groups',
        ),
        migrations.AddField(
            model_name='group',
            name='ideas',
            field=models.ManyToManyField(blank=True, related_name='groups', to='holpoint.Idea'),
        ),
        migrations.AddField(
            model_name='group',
            name='prefered_idea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='holpoint.Idea'),
        ),
        migrations.AddField(
            model_name='idea',
            name='activities',
            field=models.ManyToManyField(blank=True, related_name='activities', to='holpoint.Activity'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='group',
            name='profiles',
            field=models.ManyToManyField(related_name='groups', to='holpoint.Profile'),
        ),
    ]
