# Generated by Django 2.2.10 on 2020-03-03 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holpoint', '0004_auto_20200302_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_comments', to='holpoint.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='IdeaComment',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='holpoint.Comment')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='holpoint.Idea')),
            ],
            bases=('holpoint.comment',),
        ),
        migrations.CreateModel(
            name='ActivityComment',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='holpoint.Comment')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='holpoint.Activity')),
            ],
            bases=('holpoint.comment',),
        ),
    ]
