# Generated by Django 2.2.10 on 2020-03-14 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holpoint', '0004_auto_20200310_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='likes',
        ),
    ]
