# Generated by Django 2.2.10 on 2020-03-15 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holpoint', '0005_auto_20200314_1523'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='voteideaingroup',
            unique_together={('idea', 'group')},
        ),
    ]
