# Generated by Django 2.2.10 on 2020-02-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holpoint', '0005_auto_20200221_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='date_finish',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='date_start',
            field=models.DateField(null=True),
        ),
    ]
