# Generated by Django 2.2.10 on 2020-03-03 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holpoint', '0006_comment_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='activities',
        ),
        migrations.AlterField(
            model_name='idea',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='holpoint.Profile'),
        ),
    ]
