# Generated by Django 2.2.10 on 2020-02-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holpoint', '0007_auto_20200221_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='date_finish',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='date_start',
            field=models.DateField(auto_now=True),
        ),
    ]
