# Generated by Django 2.2.10 on 2020-03-03 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holpoint', '0007_auto_20200303_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='holpoint.Group'),
        ),
    ]
