# Generated by Django 2.2.10 on 2020-03-16 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holpoint', '0007_auto_20200315_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Acc', 'Accepted'), ('Pen', 'Pending'), ('Ref', 'Refused')], max_length=3)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='holpoint.Profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='holpoint.Profile')),
            ],
            options={
                'unique_together': {('sender', 'receiver')},
            },
        ),
    ]
