# Generated by Django 2.2.10 on 2020-03-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holpoint', '0008_friendrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_profile_friends_+', to='holpoint.Profile'),
        ),
    ]
