# Generated by Django 2.2.10 on 2020-02-25 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holpoint', '0008_auto_20200221_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_activities', to='holpoint.Profile'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='holpoint.Group'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='holpoint.Idea'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_activities', to='holpoint.Profile'),
        ),
        migrations.AlterField(
            model_name='group',
            name='admins',
            field=models.ManyToManyField(related_name='admin_groups', to='holpoint.Profile'),
        ),
        migrations.AlterField(
            model_name='group',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to='holpoint.Profile'),
        ),
        migrations.AlterField(
            model_name='group',
            name='profiles',
            field=models.ManyToManyField(related_name='groups', to='holpoint.Profile'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_ideas', to='holpoint.Profile'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='groups', to='holpoint.Group'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_ideas', to='holpoint.Profile'),
        ),
    ]
