# Generated by Django 2.2.10 on 2020-03-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holpoint', '0009_auto_20200316_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('Acc', 'Accepted'), ('Pen', 'Pending'), ('Ref', 'Refused')], default='Pen', max_length=3),
        ),
    ]
