# Generated by Django 2.2.10 on 2020-03-20 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holpoint', '0011_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='datetime',
        ),
        migrations.AddField(
            model_name='activity',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='kind',
            field=models.CharField(choices=[('GEN', 'Generico'), ('SPO', 'Spostamento'), ('PER', 'Pernottamento'), ('RIS', 'Ristorante'), ('VIS', 'Visita'), ('ESC', 'Escursione'), ('SVA', 'Svago'), ('ACQ', 'Acquisti')], default='GEN', max_length=3),
        ),
        migrations.AddField(
            model_name='activity',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='activity_attachments')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='holpoint.Activity')),
            ],
        ),
    ]
