# Generated by Django 2.2.10 on 2020-03-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holpoint', '0012_auto_20200320_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
