# Generated by Django 2.2.10 on 2020-03-23 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holpoint', '0014_auto_20200322_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='activity',
        ),
        migrations.AddField(
            model_name='attachment',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='holpoint.Group'),
            preserve_default=False,
        ),
    ]
