# Generated by Django 2.2.10 on 2020-03-23 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holpoint', '0019_attachment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_attachments', to='holpoint.Profile'),
            preserve_default=False,
        ),
    ]
