// auth
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

// alerts
export const ADD_ALERT = "ADD_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const REMOVE_ALL_ALERTS = "REMOVE_ALL_ALERTS";
export const ERROR = "ERROR";

//current user
export const GET_CURRENT_USER_START = "GET_CURRENT_USER_START";
export const GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS";
export const GET_CURRENT_USER_FAIL = "GET_CURRENT_USER_FAIL";
export const GET_CURRENT_USER_LOGOUT = "GET_CURRENT_USER_LOGOUT";
export const PUT_CURRENT_USER = "PUT_CURRENT_USER";
export const LOADING = "LOADING";
export const DONE = "DONE";
export const ADD_FRIEND_TO_STORE = "ADD_FRIEND_TO_STORE";
export const REMOVE_FRIEND_FROM_STORE = "REMOVE_FRIEND_FROM_STORE";
export const PICTURE_UPDATE = "PICTURE_UPDATE";
export const ADD_IDEA_TO_STORE = "ADD_IDEA_TO_STORE";
export const REMOVE_IDEA_FROM_STORE = "REMOVE_IDEA_FROM_STORE";

//friend_requests
export const GET_FRIEND_REQUESTS = "GET_FRIEND_REQUESTS";
export const POST_FRIEND_REQUEST = "POST_FRIEND_REQUEST";
export const PUT_FRIEND_REQUEST = "PUT_FRIEND_REQUEST";
export const CLEAR_FRIEND_REQUESTS = "CLEAR_FRIEND_REQUESTS";
